require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Rakefile
  NewCops: disable
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.7
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Lint/MissingCopEnableDirective:
  Enabled: false
Layout/LineLength:
  Enabled: false
# https://github.com/rubocop-hq/rubocop-rails/issues/348
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/SkipsModelValidations:
  AllowedMethods:
  - update_all
