version: '3.8'

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      RUBY_VERSION: '2.7.2'

x-rails: &rails
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - bundle:/bundle
    - .:/app
  environment:
    PG_HOST: postgres
  depends_on:
    - postgres

services:
  server:
    <<: *rails
    container_name: api_github_app
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec puma -C config/puma.rb"
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    container_name: api_github_db
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  bundle:
  postgres:
