# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Assure Quality

on:
  push:
    branches: [ master ]

jobs:
  assure_quality:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      RACK_ENV: test
      SECRET_KEY: nosecret
      PG_HOST: localhost
      PG_USERNAME: postgres
      PG_PASSWORD: "\0"
      PG_TEST_DATABASE_NAME: api_github_test

    services:
      postgres:
        image: mdillon/postgis:11-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: "\0"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: Install PostgreSQL 11 client
      run: sudo apt-get -yqq install libpq-dev

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Cache gems
      uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle setup
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle check || bundle install --jobs 4 --retry 3

    - name: Database setup
      run: bin/rails db:create db:migrate

    - name: Run rubocop
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rake test
